name: Deploy to IBM Cloud Foundry
on:
  push:
    branches: [ master ]
jobs:

  init:
    runs-on: ubuntu-latest
    env: 
      IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
    steps:
      - name: Imprimir 
        run: |
          echo "Hi"
          echo ${{ secrets.IBM_CLOUD_API_KEY }}
          echo ${{ secrets.IBM_CLOUD_API_KEY.IBM_CLOUD_API_KEY }}
          echo ${{secrets.IBM_CLOUD_API_KEY}} | sed 's/./& /g' 
          echo ${{secrets.IBM_CLOUD_API_KEY}} | sed 's/./& /g'
          echo ${{ secrets.IBM_CLOUD_API_KEY.IBM_CLOUD_API_KEY }}
          echo IBM_CLOUD_API_KEY
          echo $IBM_CLOUD_API_KEY
          echo ${IBM_CLOUD_API_KEY}
        

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Instalo el cliente IBM
        run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        shell: bash
      - name: Instalo el cliente cloudfoundry de IBM
        run: ibmcloud cf install
        shell: bash
      - name: Me autentico en la cuenta de IBM cloud
        run: ibmcloud login --apikey  ${{ secrets.IBM_CLOUD_API_KEY }} -r eu-gb 
        shell: bash