name: Deploy to IBM Cloud Foundry
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy MyApp
      uses: subhamx/ibm-cloud-foundry-deploy@master
      with:
        # # For Users who have opted for Authentication using Email & Password
        EMAIL: ${{ secrets.IBM_CLOUD_API_KEY.USER_EMAIL }}
        PASSWORD: ${{ secrets.IBM_CLOUD_API_KEY.USER_PASSWORD }}
        # # For Users who have opted for Authentication using API KEY
        # IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        # Cloud Foundry API Endpoint
        CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
        # Path to manifest.yml
        MANIFEST_FILE_PATH: './manifest.yml'
        # Cloud Foundry ORG Name
        ORG: 'joseinn@correo.ugr.es'
        # Cloud Foundry Space Name for the specified ORG
        SPACE: '1'