name: Deploy to IBM Cloud Foundry
on:
  push:
    branches: [ master ]
jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir 
        run: |
          echo "Hi"
          echo ${{ secrets.IBM_CLOUD_API_KEY }}
          echo ${{ secrets.IBM_CLOUD_API_KEY.IBM_CLOUD_API_KEY }}

  deploy:
    runs-on: ubuntu-latest
    env: 
      IBM_CLOUD_API_KEY: ${{ secrets.SECRET_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to IBM Cloud Foundry
        # You may pin to the exact commit or the version.
        uses: IBM/cloudfoundry-deploy@master
        with:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          IBM_CLOUD_CF_ORG: 'joseinn@correo.ugr.es'
          IBM_CLOUD_CF_SPACE: '1'