name: Deploy to IBM Cloud Foundry
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Instalo el cliente IBM
        run: | 
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
      - name: Instalo el cliente cloudfoundry de IBM
        run: | 
          ibmcloud cf install
      - name: Me autentico en la cuenta de IBM cloud
        run: |
          ibmcloud login --apikey  ${{ secrets.IBM_CLOUD_API_KEY }} -r eu-gb 
        # Se puede obtener el target con ibmcloud resource groups
      - name: Asocio el target
        run: |
          echo "If you want to know the target id of your project execute ibmcloud resource group and collect the associated ID"
          ibmcloud target -g $${{ secrets.IBM_CLOUD_TARGET_ID}}
      - name: Despliego en Cloud Foundry
        run: |
          ibmcloud cf push 
